parser: "@typescript-eslint/parser"

parserOptions:
  project:
    - ./tsconfig.json
    - ./.storybook/tsconfig.json

extends:
  - "@abrahamtewa/eslint-config/typescript"

ignorePatterns:
  - "!.storybook"
