# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    desc: Build the bundle
    cmds:
      - npm run build

  clean:
    desc: Remove all generated files
    cmds:
      - rm -rf dist
      - rm -rf reports
      - rm *.tgz

  default:
    aliases:
      - "dev"
    desc: Start the development server
    cmds:
      - vite
    silent: true

  lint:
    desc: Run the linter
    cmds:
      - npm run lint

  list:
    desc: List all tasks (shortcut for task --list-all)
    cmds:
      - task --list-all

  storybook:
    desc: Run the test suite
    aliases:
      - "sb"
    cmds:
      - npm run storybook

  test:
    desc: Run the test suite
    cmds:
      - npm test

  validate:
    desc: Run all validation tasks
    cmds:
        - npm run lint
        - npm run build
        - npm run test
